[WIP] chore: add a new dynamic page to render the right hustler by id
dopedao/dope-monorepo pull request #128
Opened 2021-11-24 22:10 UTC by smakosh

## To Do
- [x] Create a new page at /hustlers/<id>/customize for updating the hustlers configuration.
- [ ] We can reuse the existing customization components.
> If the user is minting a new one, it should use the L1 mintTo, if they are customizing, it should use the L2 hustlers contract with setMetadata
- [ ] The existing configuration can be pulled from: https://github.com/dopedao/dope-monorepo/blob/master/packages/contracts/dist/Hustler.d.ts#L335 (but i'll update the subgraph to pull the metadata too)
- [ ] And updated with: https://github.com/dopedao/dope-monorepo/blob/master/packages/contracts/dist/Hustler.d.ts#L383

2021-11-30 07:21 UTC, subimage requested changes
@smakosh Looks like this is still in progress but here are the things I noticed…

[] On main net clicking my hustler brought up a random ID, not the hustler I wanted to configure
[] Configuration controls don't seem to work…

Let me know how I can help move this forward.

2021-12-02 01:24 UTC, smakosh commented
> @smakosh Looks like this is still in progress but here are the things I noticed…
> 
> [] On main net clicking my hustler brought up a random ID, not the hustler I wanted to configure [] Configuration controls don't seem to work…
> 
> Let me know how I can help move this forward.

These have been now fixed

2021-12-04 03:14 UTC, tarrencev commented on packages/web/components/hustler/RenderFromItemIds.tsx
> +          renderName ? name : '', // title
we should get the ogs title from the metadata

2021-12-04 04:01 UTC, tarrencev commented on packages/web/hooks/contracts.ts
> +    const metadata = await hustler.metadata(id);
we can get the OGs title off the Components contract for now: https://github.com/dopedao/dope-monorepo/blob/master/packages/contracts/src/Components.sol#L386

2021-12-06 15:30 UTC, smakosh commented on packages/web/features/hustlers/components/ConfigureHustler/index.tsx
> +    router.replace('/hustlers/mint-success');
What do you suggest we do once you're done customizing your hustler?

2021-12-08 21:11 UTC, smakosh commented
Closing in favor of https://github.com/dopedao/dope-monorepo/pull/136

2021-12-08 21:11 UTC, closed without merging