feat: add hustler details/gear page version: 1
dopedao/dope-monorepo pull request #233
Opened 2022-01-26 13:55 UTC by cmarouan

This pull request contains the first version of the hustler details + gear using Dope tabs:

Remarks:

- The respect field has not returned at the moment from the backend
- Hustler's Tier color in Gears needs to be fixed on the backend side after that the color will be displayed in the frontend (already implemented in the front)

Todo:

- Dope tabs mobile style
- Dope tabs should be integrated with the header
- The actions should be added to the buttons (at the moment only the display)

2022-01-26 14:01 UTC, smakosh requested changes
Left some notes, will add more once the first ones are fixed.

Also let's server side render this page using getServerSideProps Next js API.

2022-01-26 14:01 UTC, smakosh commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/SellHustler.tsx
> +    <Button type="button" variant="primary" loadingText="Processing..." w="100%">
This should accept onClick prop

2022-01-26 14:01 UTC, smakosh commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/index.tsx
> +import SellHustler from './SellHustler';
Can we stick with absolute imports?

2022-01-26 14:01 UTC, smakosh commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/index.tsx
> +export default function index() {
ES6 arrow function

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/components/hustler/ZoomControls.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
done

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/HustlerDetails.tsx
> +}
done

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/HustlerDetails.tsx
> +  const [details, _] = useState(formatHustlerDetails(porps));
done

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/HustlerDetails.tsx
> +        <div />
👀

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/HustlerInformationTabs.tsx
> +export default function HustlerInformationTabs({ huslter }: HustlerInformationTabsProps) {
done

2022-01-26 22:31 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/SellHustler.tsx
> +export default function SellHustler() {
done

2022-01-26 22:32 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/SellHustler.tsx
> +    <Button type="button" variant="primary" loadingText="Processing..." w="100%">
done

2022-01-26 22:32 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/index.tsx
> +import SellHustler from './SellHustler';
sure !

2022-01-26 22:32 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/actions/index.tsx
> +export default function index() {
:D

2022-01-26 22:33 UTC, cmarouan commented on packages/web/src/features/hustlers/components/HustlerInformation/HustlerGear.tsx
> +        <Button type="button" variant="primary" loadingText="Processing...">
The form will be added once the actions are integrated for sure! thanks for the remark

2022-01-27 07:30 UTC, smakosh approved these changes
LGTM

2022-04-02 19:53 UTC, closed without merging

2022-04-02 19:54 UTC, subimage commented
Closing PR because code did not match design. Already working on this in another branch.